version: '3.8'

name: lilibre

services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password!
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - ./.volumes/mssql/data:/var/opt/mssql/data
      - ./.volumes/mssql/log:/var/opt/mssql/log
      - ./.volumes/mssql/secrets:/var/opt/mssql/secrets
    restart: unless-stopped

  api:
    container_name: api
    depends_on:
      - mssql
    build:
      context: ./src/Api/
      dockerfile: Dockerfile
    ports:
      - 5000:80

  web:
    container_name: web
    depends_on:
      - api
    build:
      context: ./src/Web/web/
      dockerfile: Dockerfile
    ports:
      - 5001:80
